version: '3'
services:
  mongodb:
    image: mongo
    container_name: ecommerce_db
    ports: 
      - 27017:27017
    volumes: 
      - ./data:/data/db  
    environment:
      MONGO_USER: 'admin'
      MONGO_PASSWORD: 'admin_123'  